# Generated by Django 6.0.5 on 2026-06-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_room'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='unique_room_name_per_location'),
        ),
    ]
